# This file was generated by squirrel_ex from test/fixtures/sql/all_posts.sql. DO NOT EDIT.
defmodule SquirrelEx.Test.Sql.AllPosts do
  @moduledoc """
  All posts, newest first.

  Generated from `test/fixtures/sql/all_posts.sql`.
  """

  @sql ~S"""
  -- All posts, newest first.
  select id, title, body from posts order by title
  """

  @type row :: %{id: String.t(), title: String.t(), body: String.t() | nil}

  @spec run(repo :: Ecto.Repo.t()) ::
          {:ok, [row()]} | {:error, term()}
  def run(repo) do
    case Ecto.Adapters.SQL.query(repo, @sql, []) do
      {:ok, %{columns: cols, rows: rows}} ->
        keys = Enum.map(cols, &String.to_atom/1)
        {:ok, Enum.map(rows, fn row -> keys |> Enum.zip(row) |> Map.new() end)}

      {:error, _} = error ->
        error
    end
  end
end
