# This file was generated by squirrel_ex from test/fixtures/sql/all_posts.sql. DO NOT EDIT.
defmodule SquirrelEx.Test.Sql.AllPosts do
  @moduledoc """
  All posts, newest first.

  Generated from `test/fixtures/sql/all_posts.sql`.
  """

  @sql ~S"""
  -- All posts, newest first.
  select id, title, body from posts order by title
  """

  defmodule Row do
    @enforce_keys [:id, :title, :body]
    defstruct [:id, :title, :body]

    @type t :: %__MODULE__{
            id: String.t(),
            title: String.t(),
            body: String.t() | nil
          }
  end

  @type row :: __MODULE__.Row.t()

  @doc false
  @spec __squirrel__() :: %{sql: String.t(), params: [map()], columns: [map()]}
  def __squirrel__ do
    %{
      sql: @sql,
      params: [],
      columns: [
        %{name: "id", type: "String.t()", ecto: Ecto.UUID, nullable: false, enum: nil},
        %{name: "title", type: "String.t()", ecto: :string, nullable: false, enum: nil},
        %{name: "body", type: "String.t() | nil", ecto: :string, nullable: true, enum: nil}
      ]
    }
  end

  @spec run(repo :: Ecto.Repo.t()) ::
          {:ok, [row()]} | {:error, term()}
  def run(repo) do
    case Ecto.Adapters.SQL.query(repo, @sql, []) do
      {:ok, %{rows: rows}} ->
        {:ok, Enum.map(rows, &build_row/1)}

      {:error, _} = error ->
        error
    end
  end

  defp build_row([v0, v1, v2]) do
    %Row{
      id: v0,
      title: v1,
      body: v2
    }
  end
end
