defmodule SquirrelEx.MixProject do
  use Mix.Project

  @version "0.1.0"
  @source_url "https://github.com/ken-kost/squirrel_ex"

  def project do
    [
      app: :squirrel_ex,
      version: @version,
      elixir: "~> 1.20",
      start_permanent: Mix.env() == :prod,
      elixirc_paths: elixirc_paths(Mix.env()),
      deps: deps(),
      description:
        "Type-safe SQL for Elixir: write .sql files, get typed wrappers generated by introspecting PostgreSQL.",
      package: package(),
      name: "SquirrelEx",
      source_url: @source_url,
      docs: [main: "SquirrelEx", extras: ["README.md"]]
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support", "test/fixtures/sql"]
  defp elixirc_paths(_), do: ["lib"]

  defp deps do
    [
      {:postgrex, "~> 0.20"},
      {:ecto_sql, "~> 3.13"},
      {:telemetry, "~> 1.0"},
      {:file_system, "~> 1.0"},
      {:ex_doc, "~> 0.34", only: :dev, runtime: false}
    ]
  end

  defp package do
    [
      licenses: ["Apache-2.0"],
      links: %{"GitHub" => @source_url}
    ]
  end
end
