defmodule SquirrelEx.MixProject do
  use Mix.Project

  @version "0.1.0"
  @source_url "https://github.com/ken-kost/squirrel_ex"

  def project do
    [
      app: :squirrel_ex,
      version: @version,
      elixir: "~> 1.20-rc",
      start_permanent: Mix.env() == :prod,
      elixirc_paths: elixirc_paths(Mix.env()),
      deps: deps(),
      description:
        "Type-safe SQL for Elixir: write .sql files, get typed wrappers generated by introspecting PostgreSQL.",
      package: package(),
      name: "SquirrelEx",
      source_url: @source_url,
      docs: [main: "SquirrelEx", extras: ["README.md"]]
    ]
  end

  # NOTE: we intentionally do NOT register the `:squirrel_ex` compiler here.
  # This project *defines* the compiler, so on a clean build the compiler task
  # module does not exist yet (chicken-and-egg). Host applications add it via
  # `compilers: [:squirrel_ex] ++ Mix.compilers()`. Our tests drive the compiler
  # directly. See README for host setup.

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Compile test fixtures (committed generated modules) and support helpers
  # only in the test environment.
  defp elixirc_paths(:test), do: ["lib", "test/support", "test/fixtures/sql"]
  defp elixirc_paths(_), do: ["lib"]

  defp deps do
    [
      # Compile-time introspection of PostgreSQL.
      {:postgrex, "~> 0.20"},
      # Runtime execution of the generated queries (Ecto.Adapters.SQL.query/4)
      # and the Ecto.UUID type used in generated specs.
      {:ecto_sql, "~> 3.13"},
      # Build-time visibility around introspection (also a transitive dep).
      {:telemetry, "~> 1.0"},
      # Powers `mix squirrel_ex.watch` (regenerate on .sql change).
      {:file_system, "~> 1.0"},
      {:ex_doc, "~> 0.34", only: :dev, runtime: false}
    ]
  end

  defp package do
    [
      licenses: ["Apache-2.0"],
      links: %{"GitHub" => @source_url}
    ]
  end
end
