defmodule SquirrelEx.Codegen do
  @moduledoc """
  Turns a `SquirrelEx.Query` into the source of its generated wrapper module.

  Emits a module exposing a typed `run/N` that calls `Ecto.Adapters.SQL.query/4`.
  Rows are returned as a generated struct (`<Query>.Row`) by default, or as plain
  maps when `row_type: :map`. Enum columns are decoded to atoms. A `-- @one`
  directive switches `run/N` to return a single row (or `nil`) instead of a list.

  Every generated module also defines a machine-readable `__squirrel__/0`
  accessor returning `%{sql, params, columns}`, so downstream tooling never has
  to re-introspect or parse the generated source.

  With `mode: :metadata`, the module carries only the types and `__squirrel__/0`
  — no `run/N` — for consumers that just want the typing.

  Output is run through `Code.format_string!/1`, so it is always
  formatter-clean and stable enough for snapshot testing.
  """

  alias SquirrelEx.Query

  @header "# This file was generated by squirrel_ex"

  @doc "The marker line every generated file begins with, used to guard against clobbering hand-edited files."
  @spec header() :: String.t()
  def header, do: @header

  @doc """
  Generates the full source for the wrapper module of `query`.
  """
  @spec generate(Query.t()) :: String.t()
  def generate(%Query{mode: :metadata} = query) do
    """
    #{@header} from #{query.rel_path}. DO NOT EDIT.
    defmodule #{query.module} do
      @moduledoc #{moduledoc(query)}

      @sql #{sql_heredoc(query.sql)}
      #{row_module(query)}
      #{row_type(query)}
      #{squirrel_meta(query)}
    end
    """
    |> format()
  end

  def generate(%Query{} = query) do
    """
    #{@header} from #{query.rel_path}. DO NOT EDIT.
    defmodule #{query.module} do
      @moduledoc #{moduledoc(query)}

      @sql #{sql_heredoc(query.sql)}
      #{row_module(query)}
      #{row_type(query)}
      #{squirrel_meta(query)}

      @spec run(#{spec_args(query)}) ::
              {:ok, #{return_type(query)}} | {:error, term()}
      def run(#{run_args(query)}) do
        case Ecto.Adapters.SQL.query(#{query_args(query)}) do
          #{success_clause(query)}

          {:error, _} = error ->
            error
        end
      end
      #{row_builder(query)}#{decoders(query)}
    end
    """
    |> format()
  end

  defp format(source) do
    source
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> Kernel.<>("\n")
  end

  # A machine-readable metadata accessor for downstream tooling (e.g. an Ash
  # extension): the raw SQL, the parameters, and the columns with their types,
  # nullability, and enum variants. Avoids re-introspecting or parsing the source.
  defp squirrel_meta(%Query{} = query) do
    params =
      Enum.map_join(query.params, ", ", fn p ->
        "%{name: #{inspect(p.name)}, type: #{inspect(p.typespec)}}"
      end)

    columns =
      Enum.map_join(query.columns, ", ", fn c ->
        "%{name: #{inspect(c.key)}, type: #{inspect(c.typespec)}, nullable: #{c.nullable}, enum: #{inspect(c.enum)}}"
      end)

    """

      @doc false
      @spec __squirrel__() :: %{sql: String.t(), params: [map()], columns: [map()]}
      def __squirrel__ do
        %{sql: @sql, params: [#{params}], columns: [#{columns}]}
      end
    """
  end

  defp moduledoc(%Query{doc: nil} = query) do
    inspect("Generated from `#{query.rel_path}`.")
  end

  defp moduledoc(%Query{doc: doc} = query) do
    ~s("""\n  #{doc}\n\n  Generated from `#{query.rel_path}`.\n  """)
  end

  defp sql_heredoc(sql) do
    indented = sql |> String.split("\n") |> Enum.map_join("\n", &("  " <> &1))
    ~s(~S"""\n#{indented}\n  """)
  end

  # --- row shape -----------------------------------------------------------

  # A generated `Row` struct, only for the :struct row type with columns.
  defp row_module(%Query{row_type: :struct, columns: [_ | _] = columns}) do
    keys = Enum.map(columns, &atom_key(&1.key))

    fields =
      Enum.map_join(columns, ",\n          ", fn c -> "#{atom_key(c.key)}: #{c.typespec}" end)

    """

      defmodule Row do
        @enforce_keys #{inspect_keys(keys)}
        defstruct #{inspect_keys(keys)}

        @type t :: %__MODULE__{
                #{fields}
              }
      end
    """
  end

  defp row_module(%Query{}), do: ""

  defp row_type(%Query{columns: []}), do: "@type row :: %{}"
  defp row_type(%Query{row_type: :struct}), do: "@type row :: __MODULE__.Row.t()"

  defp row_type(%Query{columns: columns}) do
    fields = Enum.map_join(columns, ", ", fn c -> "#{atom_key(c.key)}: #{c.typespec}" end)
    "@type row :: %{#{fields}}"
  end

  # --- run/N signature -----------------------------------------------------

  defp return_type(%Query{columns: []}), do: "non_neg_integer()"
  defp return_type(%Query{one: true}), do: "row() | nil"
  defp return_type(%Query{}), do: "[row()]"

  defp spec_args(%Query{} = query) do
    args = repo_arg(query, "repo :: Ecto.Repo.t()") ++ typed_params(query)
    Enum.join(args, ", ")
  end

  defp typed_params(%Query{params: params}) do
    Enum.map(params, &"#{&1.name} :: #{&1.typespec}")
  end

  defp run_args(%Query{} = query) do
    args = repo_arg(query, "repo") ++ Enum.map(query.params, & &1.name)
    Enum.join(args, ", ")
  end

  defp query_args(%Query{} = query) do
    repo = if query.repo, do: inspect(query.repo), else: "repo"
    "#{repo}, @sql, [#{Enum.map_join(query.params, ", ", & &1.name)}]"
  end

  defp repo_arg(%Query{repo: nil}, arg), do: [arg]
  defp repo_arg(%Query{}, _arg), do: []

  # --- run/N body ----------------------------------------------------------

  # Zero-column queries (DML without RETURNING): return the affected row count.
  defp success_clause(%Query{columns: []}) do
    "{:ok, %{num_rows: n}} ->\n        {:ok, n}"
  end

  defp success_clause(%Query{one: true}) do
    """
    {:ok, %{rows: [first | _]}} ->
            {:ok, build_row(first)}

          {:ok, %{rows: _}} ->
            {:ok, nil}\
    """
  end

  defp success_clause(%Query{}) do
    """
    {:ok, %{rows: rows}} ->
            {:ok, Enum.map(rows, &build_row/1)}\
    """
  end

  # A private build_row/1 that turns a raw value list into a struct or map,
  # applying per-column decoders. Omitted for zero-column queries.
  defp row_builder(%Query{columns: []}), do: ""

  defp row_builder(%Query{columns: columns} = query) do
    vars = Enum.with_index(columns, fn _c, i -> "v#{i}" end)
    pattern = "[" <> Enum.join(vars, ", ") <> "]"

    fields =
      columns
      |> Enum.with_index()
      |> Enum.map_join(",\n      ", fn {c, i} ->
        "#{atom_key(c.key)}: #{value_expr(c, "v#{i}")}"
      end)

    open = if query.row_type == :struct, do: "%Row{", else: "%{"

    """

      defp build_row(#{pattern}) do
        #{open}
          #{fields}
        }
      end
    """
  end

  # Per-column value expression, applying the decoder.
  defp value_expr(%{decoder: :identity}, var), do: var
  defp value_expr(%{decoder: :enum, key: key}, var), do: "decode_#{decoder_name(key)}(#{var})"

  defp value_expr(%{decoder: :enum_array, key: key}, var),
    do: "decode_#{decoder_name(key)}(#{var})"

  # Private decoder functions for enum columns.
  defp decoders(%Query{columns: columns}) do
    columns
    |> Enum.filter(&(&1.decoder in [:enum, :enum_array]))
    |> Enum.uniq_by(& &1.key)
    |> Enum.map_join("", &decoder_fun/1)
  end

  defp decoder_fun(%{decoder: :enum, key: key, enum: variants}) do
    name = "decode_#{decoder_name(key)}"

    # Explicit string -> atom clauses intern the variant atoms at compile time
    # (so we never rely on String.to_existing_atom finding them) and map them.
    """

      defp #{name}(nil), do: nil
    #{variant_clauses(name, variants)}
      defp #{name}(other), do: String.to_atom(other)
    """
  end

  defp decoder_fun(%{decoder: :enum_array, key: key, enum: variants}) do
    name = "decode_#{decoder_name(key)}"
    elem = "#{name}_elem"

    """

      defp #{name}(nil), do: nil
      defp #{name}(value), do: Enum.map(value, &#{elem}/1)
    #{variant_clauses(elem, variants)}
      defp #{elem}(other), do: String.to_atom(other)
    """
  end

  defp variant_clauses(_name, nil), do: ""

  defp variant_clauses(name, variants) do
    Enum.map_join(variants, "\n", fn v -> "  defp #{name}(#{inspect(v)}), do: :#{atomish(v)}" end)
  end

  defp atomish(label) do
    if Regex.match?(~r/\A[a-zA-Z_][a-zA-Z0-9_]*[?!]?\z/, label) do
      label
    else
      inspect(label) |> String.replace_prefix(":", "")
    end
  end

  defp decoder_name(key) do
    key
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9_]/, "_")
  end

  # --- helpers -------------------------------------------------------------

  defp inspect_keys(keys) do
    "[" <> Enum.map_join(keys, ", ", &":#{&1}") <> "]"
  end

  defp atom_key(key) do
    if Regex.match?(~r/\A[a-zA-Z_][a-zA-Z0-9_]*\z/, key) do
      key
    else
      inspect(key)
    end
  end
end
