defmodule SquirrelEx.Codegen do
  @moduledoc """
  Turns a `SquirrelEx.Query` into the source of its generated wrapper module.

  Output is run through `Code.format_string!/1`, so it is always
  formatter-clean and stable enough for snapshot testing.
  """

  alias SquirrelEx.Query

  @doc """
  Generates the full source for the wrapper module of `query`.
  """
  @spec generate(Query.t()) :: String.t()
  def generate(%Query{} = query) do
    args = Enum.map(query.params, & &1.name)
    arg_vars = Enum.join(["repo" | args], ", ")

    body = """
    # This file was generated by squirrel_ex from #{query.rel_path}. DO NOT EDIT.
    defmodule #{query.module} do
      @moduledoc #{moduledoc(query)}

      @sql #{sql_heredoc(query.sql)}

      #{row_type(query)}

      @spec run(#{spec_args(query)}) ::
              {:ok, [#{result_type(query)}]} | {:error, term()}
      def run(#{arg_vars}) do
        case Ecto.Adapters.SQL.query(repo, @sql, [#{Enum.join(args, ", ")}]) do
          #{success_clause(query)}

          {:error, _} = error ->
            error
        end
      end
    end
    """

    body
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> Kernel.<>("\n")
  end

  defp moduledoc(%Query{doc: nil} = query) do
    inspect("Generated from `#{query.rel_path}`.")
  end

  defp moduledoc(%Query{doc: doc} = query) do
    ~s("""\n  #{doc}\n\n  Generated from `#{query.rel_path}`.\n  """)
  end

  defp sql_heredoc(sql) do
    indented = sql |> String.split("\n") |> Enum.map_join("\n", &("  " <> &1))
    ~s(~S"""\n#{indented}\n  """)
  end

  # When the query returns no columns (e.g. INSERT without RETURNING) we still
  # define a row type for documentation, but it is an empty map.
  defp row_type(%Query{columns: []}) do
    "@type row :: %{}"
  end

  defp row_type(%Query{columns: columns}) do
    fields = Enum.map_join(columns, ", ", fn c -> "#{atom_key(c.key)}: #{c.typespec}" end)
    "@type row :: %{#{fields}}"
  end

  defp result_type(%Query{}), do: "row()"

  defp spec_args(%Query{params: params}) do
    ["repo :: Ecto.Repo.t()" | Enum.map(params, &"#{&1.name} :: #{&1.typespec}")]
    |> Enum.join(", ")
  end

  defp success_clause(%Query{}) do
    """
    {:ok, %{columns: cols, rows: rows}} ->
            keys = Enum.map(cols, &String.to_atom/1)
            {:ok, Enum.map(rows, fn row -> keys |> Enum.zip(row) |> Map.new() end)}\
    """
  end

  defp atom_key(key) do
    if Regex.match?(~r/\A[a-zA-Z_][a-zA-Z0-9_]*\z/, key) do
      key
    else
      inspect(key)
    end
  end
end
