# This file was generated by squirrel_ex from priv/sql/list_posts.sql. DO NOT EDIT.
defmodule MyApp.Sql.ListPosts do
  @moduledoc """
  List a post's id, title and (nullable) body by author.

  Generated from `priv/sql/list_posts.sql`.
  """

  @sql ~S"""
  -- List a post's id, title and (nullable) body by author.
  select id, title, body from posts where author_id = $1 order by title
  """

  @type row :: %{id: String.t(), title: String.t(), body: String.t() | nil}

  @spec run(repo :: Ecto.Repo.t(), author_id :: integer()) ::
          {:ok, [row()]} | {:error, term()}
  def run(repo, author_id) do
    case Ecto.Adapters.SQL.query(repo, @sql, [author_id]) do
      {:ok, %{columns: cols, rows: rows}} ->
        keys = Enum.map(cols, &String.to_atom/1)
        {:ok, Enum.map(rows, fn row -> keys |> Enum.zip(row) |> Map.new() end)}

      {:error, _} = error ->
        error
    end
  end
end
