# This file was generated by squirrel_ex from priv/sql/list_posts.sql. DO NOT EDIT.
defmodule MyApp.Sql.ListPosts do
  @moduledoc """
  List a post's id, title and (nullable) body by author.

  Generated from `priv/sql/list_posts.sql`.
  """

  @sql ~S"""
  -- List a post's id, title and (nullable) body by author.
  select id, title, body from posts where author_id = $1 order by title
  """

  defmodule Row do
    @enforce_keys [:id, :title, :body]
    defstruct [:id, :title, :body]

    @type t :: %__MODULE__{
            id: Ecto.UUID.raw(),
            title: String.t(),
            body: String.t() | nil
          }
  end

  @type row :: __MODULE__.Row.t()

  @doc false
  @spec __squirrel__() :: %{sql: String.t(), params: [map()], columns: [map()]}
  def __squirrel__ do
    %{
      sql: @sql,
      params: [%{name: "author_id", type: "integer()", ecto: :integer}],
      columns: [
        %{name: "id", type: "Ecto.UUID.raw()", ecto: Ecto.UUID, nullable: false, enum: nil},
        %{name: "title", type: "String.t()", ecto: :string, nullable: false, enum: nil},
        %{name: "body", type: "String.t() | nil", ecto: :string, nullable: true, enum: nil}
      ]
    }
  end

  @spec run(repo :: Ecto.Repo.t(), author_id :: integer()) ::
          {:ok, [row()]} | {:error, term()}
  def run(repo, author_id) do
    case Ecto.Adapters.SQL.query(repo, @sql, [author_id]) do
      {:ok, %{rows: rows}} ->
        {:ok, Enum.map(rows, &build_row/1)}

      {:error, _} = error ->
        error
    end
  end

  defp build_row([v0, v1, v2]) do
    %Row{
      id: v0,
      title: v1,
      body: v2
    }
  end
end
