defmodule SquirrelEx.CodegenTest do
  use ExUnit.Case, async: true

  alias SquirrelEx.{Codegen, Query, Type}

  defp build(opts) do
    defaults = [
      namespace: "App.Sql",
      sql_path: "/p/list_posts.sql",
      rel_path: "priv/sql/list_posts.sql",
      clean_sql: "select 1",
      param_names: [],
      param_typespecs: []
    ]

    Query.build(Keyword.merge(defaults, opts))
  end

  defp compile_unique(source) do
    # Generated modules are namespaced per test via a unique suffix so repeated
    # compilation does not clash.
    mods = Code.compile_string(source)
    Enum.each(mods, fn {mod, _} -> :code.purge(mod) && :code.delete(mod) end)
    mods
  end

  test "generates a formatter-clean, compilable struct module by default" do
    query =
      build(
        doc: "List posts by author",
        clean_sql: "select id, title, body from posts where author_id = $1",
        param_names: ["author_id"],
        param_typespecs: ["integer()"],
        columns: [{"id", "String.t()"}, {"title", "String.t()"}, {"body", "String.t()"}],
        nullability: [:not_null, :not_null, :nullable]
      )

    source = Codegen.generate(query)

    assert source =~ "# This file was generated by squirrel_ex"
    assert source =~ "defmodule App.Sql.ListPosts do"
    assert source =~ "defmodule Row do"
    assert source =~ "@enforce_keys [:id, :title, :body]"
    assert source =~ "@type row :: __MODULE__.Row.t()"
    assert source =~ "body: String.t() | nil"
    assert source =~ "def run(repo, author_id) do"
    assert source =~ "Ecto.Adapters.SQL.query(repo, @sql, [author_id])"
    assert source =~ "{:ok, Enum.map(rows, &build_row/1)}"
    assert source =~ "%Row{"

    # Output is already formatter-clean (idempotent under the formatter).
    assert source == IO.iodata_to_binary(Code.format_string!(source)) <> "\n"

    assert [_row_mod, {App.Sql.ListPosts, _}] = compile_unique(source)
  end

  test "row_type: :map generates a plain map with no Row struct" do
    source =
      build(
        clean_sql: "select id, body from posts",
        columns: [{"id", "String.t()"}, {"body", "String.t()"}],
        nullability: [:not_null, :nullable],
        row_type: :map
      )
      |> Codegen.generate()

    refute source =~ "defmodule Row"
    assert source =~ "@type row :: %{id: String.t(), body: String.t() | nil}"
    assert source =~ "id: v0"
    assert source =~ "build_row([v0, v1])"
  end

  test "enum columns get an atom-union type and explicit variant decoder clauses" do
    enum = %Type{
      typespec: ":draft | :published",
      input: "String.t()",
      decoder: :enum,
      enum: ["draft", "published"]
    }

    source =
      build(
        clean_sql: "select id, status from posts",
        columns: [{"id", "String.t()"}, {"status", enum}],
        nullability: [:not_null, :nullable]
      )
      |> Codegen.generate()

    assert source =~ "status: :draft | :published | nil"
    assert source =~ "status: decode_status(v1)"
    assert source =~ "defp decode_status(nil), do: nil"
    assert source =~ ~s|defp decode_status("draft"), do: :draft|
    assert source =~ ~s|defp decode_status("published"), do: :published|
    assert source =~ "defp decode_status(other), do: String.to_atom(other)"
  end

  test "@one directive returns a single row or nil" do
    source =
      build(
        directives: %{one: true},
        clean_sql: "select id from posts where id = $1",
        param_names: ["id"],
        param_typespecs: ["String.t()"],
        columns: [{"id", "String.t()"}],
        nullability: [:not_null]
      )
      |> Codegen.generate()

    assert source =~ "{:ok, row() | nil} | {:error, term()}"
    assert source =~ "{:ok, %{rows: [first | _]}} ->"
    assert source =~ "{:ok, build_row(first)}"
    assert source =~ "{:ok, %{rows: _}} ->"
    assert source =~ "{:ok, nil}"
  end

  test "baking the repo drops it from run/N and uses the literal module" do
    source =
      build(
        clean_sql: "select id from posts",
        columns: [{"id", "String.t()"}],
        nullability: [:not_null],
        repo: MyApp.Repo
      )
      |> Codegen.generate()

    assert source =~ "def run() do"
    assert source =~ "Ecto.Adapters.SQL.query(MyApp.Repo, @sql, [])"
    refute source =~ "repo :: Ecto.Repo.t()"
  end

  test "zero-column queries return the affected row count" do
    source =
      build(
        clean_sql: "insert into t (a) values ($1)",
        param_names: ["a"],
        param_typespecs: ["integer()"],
        columns: []
      )
      |> Codegen.generate()

    assert source =~ "{:ok, non_neg_integer()} | {:error, term()}"
    assert source =~ "{:ok, %{num_rows: n}} ->"
    refute source =~ "build_row"
  end

  test "uses the relative path in moduledoc when there is no SQL comment" do
    source = Codegen.generate(build(doc: nil, columns: []))
    assert source =~ ~s(@moduledoc "Generated from `priv/sql/list_posts.sql`.")
  end

  test "every module exposes a machine-readable __squirrel__/0 accessor" do
    enum = %Type{
      typespec: ":draft | :published",
      decoder: :enum,
      enum: ["draft", "published"],
      ecto: Ecto.Enum
    }

    source =
      build(
        clean_sql: "select id, status from posts where author_id = $1",
        param_names: ["author_id"],
        param_types: [Type.simple("integer()", :integer)],
        # `id` is a uuid: the typespec is lossy (String.t()) but ecto carries Ecto.UUID.
        columns: [{"id", Type.simple("String.t()", Ecto.UUID)}, {"status", enum}],
        nullability: [:not_null, :nullable]
      )
      |> Codegen.generate()

    assert source =~ "def __squirrel__ do"
    assert source =~ "%{name: \"author_id\", type: \"integer()\", ecto: :integer}"
    assert source =~ "enum: [\"draft\", \"published\"]"

    [{_row, _}, {mod, _}] = compile_unique(source)
    meta = mod.__squirrel__()
    assert meta.params == [%{name: "author_id", type: "integer()", ecto: :integer}]

    # The uuid column keeps its Ecto type even though the typespec is String.t().
    assert %{name: "id", type: "String.t()", ecto: Ecto.UUID, nullable: false} = hd(meta.columns)
    assert Enum.at(meta.columns, 1).ecto == Ecto.Enum
  end

  test "mode: :metadata emits types + __squirrel__/0 but no run/N" do
    source =
      build(
        clean_sql: "select id from posts",
        columns: [{"id", "String.t()"}],
        nullability: [:not_null],
        mode: :metadata
      )
      |> Codegen.generate()

    assert source =~ "defmodule Row do"
    assert source =~ "@type row :: __MODULE__.Row.t()"
    assert source =~ "def __squirrel__ do"
    refute source =~ "def run("
    refute source =~ "Ecto.Adapters.SQL.query"

    assert [{_row, _}, {mod, _}] = compile_unique(source)
    refute function_exported?(mod, :run, 1)
  end
end
