defmodule SquirrelEx.CodegenTest do
  use ExUnit.Case, async: true

  alias SquirrelEx.{Codegen, Query}

  defp build(opts) do
    defaults = [
      namespace: "App.Sql",
      sql_path: "/p/list_posts.sql",
      rel_path: "priv/sql/list_posts.sql",
      clean_sql: "select 1",
      param_names: [],
      param_typespecs: [],
      columns: []
    ]

    Query.build(Keyword.merge(defaults, opts))
  end

  test "generates a formatter-clean, compilable module" do
    query =
      build(
        doc: "List posts by author",
        clean_sql: "select id, title, body from posts where author_id = $1",
        param_names: ["author_id"],
        param_typespecs: ["integer()"],
        columns: [{"id", "String.t()"}, {"title", "String.t()"}, {"body", "String.t() | nil"}]
      )

    source = Codegen.generate(query)

    assert source =~ "# This file was generated by squirrel_ex"
    assert source =~ "defmodule App.Sql.ListPosts do"
    assert source =~ "@type row :: %{id: String.t(), title: String.t(), body: String.t() | nil}"
    assert source =~ "def run(repo, author_id) do"
    assert source =~ "Ecto.Adapters.SQL.query(repo, @sql, [author_id])"

    # Output is already formatter-clean (idempotent under the formatter).
    assert source == IO.iodata_to_binary(Code.format_string!(source)) <> "\n"

    # And it compiles.
    [{mod, _}] = Code.compile_string(source)
    assert mod == App.Sql.ListPosts
  after
    :code.purge(App.Sql.ListPosts)
    :code.delete(App.Sql.ListPosts)
  end

  test "uses the relative path in moduledoc when there is no SQL comment" do
    source = Codegen.generate(build(doc: nil))
    assert source =~ ~s(@moduledoc "Generated from `priv/sql/list_posts.sql`.")
  end

  test "handles a query with no result columns" do
    source = Codegen.generate(build(clean_sql: "insert into t (a) values ($1)", columns: []))
    assert source =~ "@type row :: %{}"
  end
end
